In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/drive/MyDrive/DL Tutorials/insurance_data.csv')
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [4]:
df.shape

(28, 3)

In [5]:
X=df[['age','affordibility']]
y=df.bought_insurance

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
len(X_train)

22

In [8]:
len(X_test)

6

In [9]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100
X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [10]:
X_train_scaled

age  affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1
1   0.25              0
4   0.46              1
5   0.56              1
2   0.47              1
16  0.25              0
23  0.45              1
3   0.52              0
26  0.23              1
24  0.50              1
18  0.19              0
27  0.46              1
20  0.21              1
7   0.60              0
10  0.18              1
14  0.49              1
19  0.18              1
6   0.55              0

In [11]:
X_test_scaled

age  affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1
12  0.27              0

In [12]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model=Sequential()
model.add(Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [17]:
model.fit(X_test_scaled,y_test,epochs=2500)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 11ms/step - loss: 0.4146 - accuracy: 0.8333
Epoch 2/2500
1/1 [==============================] - 0s 9ms/step - loss: 0.4145 - accuracy: 0.8333
Epoch 3/2500
1/1 [==============================] - 0s 9ms/step - loss: 0.4144 - accuracy: 0.8333
Epoch 4/2500
1/1 [==============================] - 0s 9ms/step - loss: 0.4143 - accuracy: 0.8333
Epoch 5/2500
1/1 [==============================] - 0s 9ms/step - loss: 0.4142 - accuracy: 0.8333
Epoch 6/2500
1/1 [==============================] - 0s 9ms/step - loss: 0.4141 - accuracy: 0.8333
Epoch 7/2500
1/1 [==============================] - 0s 9ms/step - loss: 0.4140 - accuracy: 0.8333
Epoch 8/2500
1/1 [==============================] - 0s 9ms/step - loss: 0.4139 - accuracy: 0.8333
Epoch 9/2500
1/1 [==============================] - 0s 9ms/step - loss: 0.4138 - accuracy: 0.8333
Epoch 10/2500
1/1 [==============================] - 0s 12ms/step - loss: 0.413

In [18]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 127ms/step - loss: 0.2411 - accuracy: 1.0000


[0.24113784730434418, 1.0]

In [19]:
model.predict(X_test_scaled) #anything below 0.5 is 0(no) and above 0.5 is 1(yes)

1/1 [==============================] - 0s 63ms/step


array([[0.85639364],
       [0.80900013],
       [0.86230046],
       [0.1350791 ],
       [0.46991423],
       [0.14089188]], dtype=float32)

In [21]:
y_test #matches with the test values

9     1
25    1
8     1
21    0
0     0
12    0
Name: bought_insurance, dtype: int64

In [22]:
coef,intercept=model.get_weights()
coef,intercept
'''Thus w1= 4.887 , w2= 1.931 , b= -3.127'''

(array([[4.8875465],
        [1.9317907]], dtype=float32),
 array([-3.1275396], dtype=float32))

## **Now we'll do the same thing from scratch**

In [24]:
import math
def sigmoid(x):
  return (1 / (1 + math.exp(-x)))

In [25]:
def prediction_function(age,affordibility):
  weighted_sum = coef[0]*age + coef[1]*affordibility + intercept   # coef[0] denotes w1 , coef[1] denotes w2 and intercept denotes b
  return sigmoid(weighted_sum)                                     # pass the weighted_sum through sigmoid function

In [30]:
prediction_function(0.61,1) #compare the values with predicted test values and check whether they match

<ipython-input-24-912dcc13e8c4>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return (1 / (1 + math.exp(-x)))


0.8563936842624679

In [31]:
import numpy as np
def log_loss(true,predicted):
  epsilon=1e-15
  predicted_new= [max(i,epsilon) for i in predicted]
  predicted_new= [min(i,1-epsilon) for i in predicted_new]
  predicted_new= np.array(predicted_new)
  return -np.mean(true*np.log(predicted_new) + (1-true)*np.log(1-predicted_new))

In [32]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))

In [36]:
def gradient_descent(age,affordibility,true,epochs,loss_threshold):
  w1 = w2 = 1
  bias=0
  learning_rate= 0.01
  n = len(age)

  for i in range(epochs):
    weighted_sum = w1*age + w2*affordibility + bias
    predicted = sigmoid_numpy(weighted_sum)

    loss= log_loss(true,predicted)

    w1_derivative = (1/n)*(np.dot(np.transpose(age),(predicted-true)))
    w2_derivative = (1/n)*(np.dot(np.transpose(affordibility),(predicted-true)))

    bias_derivative = np.mean(predicted-true)

    w1 = w1 - learning_rate*w1_derivative
    w2 = w2 - learning_rate*w2_derivative
    bias = bias - learning_rate*bias_derivative

    print(f"Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}")

    if loss<=loss_threshold:
       break

  return w1,w2,bias

In [41]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,100000,0.2412)

Streaming output truncated to the last 5000 lines.
Epoch:95000,w1:10.190710750975535,w2:1.7008560893992473,bias:-5.274910091579086,loss:0.43522756441924765
Epoch:95001,w1:10.19073434000133,w2:1.7008589514899768,bias:-5.274922108489837,loss:0.4352274935131422
Epoch:95002,w1:10.190757928553731,w2:1.7008618135287743,bias:-5.274934125165637,loss:0.43522742260986463
Epoch:95003,w1:10.190781516632752,w2:1.7008646755156407,bias:-5.274946141606492,loss:0.43522735170941473
Epoch:95004,w1:10.190805104238404,w2:1.700867537450577,bias:-5.2749581578124065,loss:0.4352272808117924
Epoch:95005,w1:10.190828691370697,w2:1.7008703993335843,bias:-5.274970173783387,loss:0.4352272099169976
Epoch:95006,w1:10.190852278029643,w2:1.7008732611646633,bias:-5.274982189519439,loss:0.4352271390250302
Epoch:95007,w1:10.190875864215254,w2:1.7008761229438152,bias:-5.274994205020566,loss:0.43522706813589007
Epoch:95008,w1:10.19089944992754,w2:1.7008789846710408,bias:-5.275006220286774,loss:0.43522699724957703
Epoch:9500

(10.302941394483167, 1.714535120326534, -5.33215352024069)